name: Deploy SilverBank

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: ./backend

      - name: Check JAR existence
        id: jar-check
        working-directory: ./backend
        run: |
          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            echo "JAR_EXISTS=true" >> $GITHUB_ENV
          else
            echo "JAR_EXISTS=false" >> $GITHUB_ENV
          fi
          
      - name: List build/libs
        working-directory: ./backend
        run: ls -l build/libs/

      - name: Upload application-prod.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "backend/src/main/resources/application-prod.yml"
          target: "/home/silverbank/app/silverbank/backend/src/main/resources/"

      - name: Ensure ~/.ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
    
      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy JAR using SSH + sudo
        run: |
            scp ./backend/build/libs/silver-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/
            ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mv /tmp/silver-0.0.1-SNAPSHOT.jar /home/silverbank/app/backend/build/libs/"
        shell: bash
          
      - name: Deploy systemd service file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ".github/deploy/silverbank.service"
          target: "/home/silverbank/app/"

      - name: Restart SilverBank service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 서비스 파일 복사, 권한 설정
            sudo cp /home/silverbank/app/silverbank.service /etc/systemd/system/silverbank.service
            sudo chown root:root /etc/systemd/system/silverbank.service
            sudo chmod 644 /etc/systemd/system/silverbank.service

            # daemon reload & 서비스 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart silverbank.service
            sudo systemctl enable silverbank.service
            sudo systemctl status silverbank.service --no-pager
