name: Deploy SilverBank

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java 설정 (Gradle 사용)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # 4. Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: ./backend

      # 5. JAR 아티팩트 확인
      - name: Check JAR existence
        id: jar-check
        working-directory: ./backend
        run: |
          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            echo "JAR_EXISTS=true" >> $GITHUB_ENV
          else
            echo "JAR_EXISTS=false" >> $GITHUB_ENV
          fi
          
      # 5-1. 빌드 결과 확인
      - name: List build/libs
        working-directory: ./backend
        run: ls -l build/libs/

      # 6. application-prod.yml 업로드
      - name: Upload application-prod.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "src/main/resources/application-prod.yml"
          target: "/home/silverbank/app/"

      # 7. JAR 배포
      - name: Deploy JAR to EC2
        if: env.JAR_EXISTS == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "${{ github.workspace }}/backend/build/libs/silver-0.0.1-SNAPSHOT.jar"
          target: "/home/silverbank/app/"

          
      # 8. 서비스 파일 배포
      - name: Deploy systemd service file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ".github/deploy/silverbank.service"
          target: "/home/silverbank/app/"

      # 8. 서비스 리로드 + 재시작
      - name: Restart SilverBank service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 서비스 파일 복사, 권한 설정
            sudo cp /home/silverbank/app/silverbank.service /etc/systemd/system/silverbank.service
            sudo chown root:root /etc/systemd/system/silverbank.service
            sudo chmod 644 /etc/systemd/system/silverbank.service

            # daemon reload & 서비스 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart silverbank.service
            sudo systemctl enable silverbank.service
            sudo systemctl status silverbank.service --no-pager
